device: "cuda"
mode: "unclipSD2"
pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-unclip-small"
datapath: "examples"
save_dir: "unclipSD2Result"
seed: 0
R: 20
size: 512
lamb: 200
epsilon1: 64
epsilon2: 128
guidance_scale: 7.5
num_inference_steps: 50